"""
Abstract strategy interface for trading strategies.

Defines the contract that all trading strategies must implement.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import Literal, Any

import pandas as pd

from volatility_arbitrage.core.types import Position

@dataclass(frozen=True)
class Signal:
    """
    Trading signal generated by strategy.

    Represents an order to buy or sell an instrument.
    """

    symbol: str
    action: Literal["buy", "sell"]
    quantity: int
    reason: str = ""  # Optional explanation for the signal

    def __post_init__(self) -> None:
        """Validate signal fields."""
        if self.quantity <= 0:
            raise ValueError("Quantity must be positive")
        if self.action not in ["buy", "sell"]:
            raise ValueError("Action must be 'buy' or 'sell'")

class Strategy(ABC):
    """
    Abstract base class for trading strategies.

    All strategies must implement the generate_signals method which produces
    trading signals based on market data and current positions.
    """

    @abstractmethod
    def generate_signals(
        self,
        timestamp: datetime,
        market_data: pd.DataFrame,
        positions: dict[str, Position],
        # --- ADDED: Optional args for advanced strategies ---
        cash: float = 0.0,
        portfolio_greeks: Any = None,
    ) -> list[Signal]:
        """
        Generate trading signals for the current time step.

        Args:
            timestamp: Current timestamp
            market_data: Current market data (may include multiple symbols)
            positions: Current open positions
            cash: Current available cash (optional, defaults to 0.0)
            portfolio_greeks: Current portfolio greeks (optional, defaults to None)

        Returns:
            List of trading signals to execute
        """
        pass

    def on_trade_executed(
        self,
        timestamp: datetime,
        signal: Signal,
        executed_price: float,
    ) -> None:
        """
        Callback when a trade is executed.

        Optional hook for strategies to track their execution.

        Args:
            timestamp: Execution timestamp
            signal: Original signal
            executed_price: Actual execution price
        """
        pass

    def on_backtest_start(self, start_date: datetime, end_date: datetime) -> None:
        """
        Callback when backtest starts.

        Optional hook for strategy initialization.

        Args:
            start_date: Backtest start date
            end_date: Backtest end date
        """
        pass

    def on_backtest_end(self) -> None:
        """
        Callback when backtest ends.

        Optional hook for strategy cleanup.
        """
        pass

class BuyAndHoldStrategy(Strategy):
    """
    Simple buy-and-hold strategy for testing.

    Buys on first day and holds until end.
    """

    def __init__(self, symbol: str, quantity: int = 100) -> None:
        """
        Initialize buy-and-hold strategy.

        Args:
            symbol: Symbol to buy
            quantity: Quantity to purchase
        """
        self.symbol = symbol
        self.quantity = quantity
        self.has_bought = False

    def generate_signals(
        self,
        timestamp: datetime,
        market_data: pd.DataFrame,
        positions: dict[str, Position],
        # --- ADDED: Matching signature (ignored in this simple strategy) ---
        cash: float = 0.0,
        portfolio_greeks: Any = None,
    ) -> list[Signal]:
        """Generate signals: buy once on first day."""
        if not self.has_bought and self.symbol not in positions:
            self.has_bought = True
            return [
                Signal(
                    symbol=self.symbol,
                    action="buy",
                    quantity=self.quantity,
                    reason="Buy and hold entry",
                )
            ]
        return []